services:
  # Layanan untuk database PostgreSQL
  db:
    image: postgres:14-alpine  # Menggunakan image PostgreSQL resmi yang ringan
    container_name: expense-tracker-db
    restart: unless-stopped
    environment:
      # Kredensial ini akan digunakan oleh Go untuk terhubung
      POSTGRES_USER: user_expenses
      POSTGRES_PASSWORD: password_expenses
      POSTGRES_DB: db_expenses
    ports:
      # Memetakan port 5432 di container ke port 5432 di komputer Anda
      - "5432:5432"
    volumes:
      # Volume ini akan menyimpan data database secara permanen
      # bahkan jika container dihapus dan dibuat ulang
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: expense-tracker-app
    ports:
     - "8000:8000"  # Ganti ke 8000 supaya tidak bentrok dengan Jenkins
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
  
  # Layanan untuk Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app 

  # Layanan untuk Grafana
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - "3001:3000"
    volumes:
      # Otomatis menambahkan Prometheus sebagai data source
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  
  # layanan untuk logging
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
     - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
      - log_data:/var/log/app
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped

volumes:
  postgres_data:
  log_data:
  grafana_data:
